name: Bauen
on: [push, pull_request, workflow_dispatch]

jobs:
  windows:
    name: Windows
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2
        
      - name: Build
        run: |
          "C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\Tools\VsDevCmd.bat"
          cd src
          msbuild -m CT.sln /property:Configuration=Release /p:Platform=Win32 /p:PlatformToolset=v143
          
      - name: Pack
        run: |
          mkdir ./bin/
          cp ./src/Release/CT.exe ./bin/
          cp ./src/Resources.dll ./bin/
          cp ./src/Register4Lobby/Release/Register4Lobby.exe ./bin/
          cp ./src/readme-*.txt ./bin/

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: chicken-tournament
          path: ./bin/
